load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_macro_library", "scala_test")

scala_macro_library(
    name = "codereporting",
    srcs = glob(["*.scala"]),
    visibility = ["//visibility:public"]
)
