load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_binary", "scala_test")

scala_library(
    name = "resource",
    srcs = glob(["*.scala"]),
    deps = ["//ip/eitherops:eitherops"],
    visibility = ["//visibility:public"]
)


